# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{4f75c088-8d2f-41c7-ac89-2218aa967bb1}',
        'contract_ids': ['@mozilla.org/ferifox/test-utils;1'],
        'interfaces': ['nsIFerifoxTestUtils'],
        'type': 'mozilla::FerifoxTestUtils',
        'headers': ['mozilla/FerifoxTestUtils.h'],
        'processes': ProcessSelector.ANY_PROCESS,
    },
]
